before_install:
- echo "BEFORE INSTALL START"
- openssl aes-256-cbc -K $encrypted_4d4afe80b719_key -iv $encrypted_4d4afe80b719_iv
  -in deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
- ssh 'root@172.104.191.90' docker stop nodeapp
- ssh 'root@172.104.191.90' docker rm nodeapp
- ssh 'root@172.104.191.90' docker pull tuannnh/nodejs-api
env:
  global:
  - secure: odISc0kWmo1WqfyQSValaLhlXlZaONJ7W8HbeRar8RtY1MjCTxpCAKEnoZUjSpaoK1Q5ujqbeVnHSRUzVYEdUlh6Zf5ewZnO43yzWFuUKMWptcKwwJaKRDLDCzRHMoxPquuWuo6xwflXDJ0ODCWvaUNunrWoV9NHZ2m0frjPeLUB6ofRTRIpvz3SpwzF6d5LJucX64AQ/gkdoXg3gTkRmCCjSRea5JWqFJXTDDMwHFsSJTG/fq80JtH1sKOiTE6/C1q1HyAImqqvsqa++nVvcxiFfBQ2IDM12wWwwgSLNU8oqEtfgCZCGBUgyGl4ZBFc2jpho8H2ABnFIKcN5VrM00zoVzlIspGwgYJgqys6LdZ8o+m1wRjyVG1LeA44uTJDSYoWD6+nUIfiMHjZqjL8VISR2U+loIjrr8A2KUipPIfx5uB08BFIQRjlHxQsVt9fFf7QqG+QssH57n5EiedGGG2zU8S69zRYVBQ8JFS/hTFbqgtopDnWHdmPS0fKuFBG7NLxoK+FTgJNZmg8+ABK+FfNrr3y9AckX0hoYy38GP5g5FiwhSapSu9X7D3Gn5sHRSinlzy5PJvgk0LIzEO8I+JDph0FQI45Y27KvPE54sJNNdTLDf1/KazhwiSGo9DluXvLK3AIlC9uNH8Qy7+Naw94wJhD/PD6LRObaNhSPxY=
  - secure: CEMkDjnSZPFybZ/E5VQ9YOiyrXML2Vso13eU4eTZTtTVZTZD+arX9cjNv83ByX8fFteFjBm0duoshejFD3UjM4jQ6mAyG6keamPWgXgqpDHHVTVU4LYn5MmsVPgw0Wx4LE18L+m59oDD6m3unfjGTz8Qfrmg9PsVH5UKNgTfw7yhcHNNoBS1/tpgp+8BVfe4e+YTNw0zGExTFqnEzP3WZiZ0V4fGu5QVqLzqrytFhOCiyL/JWDCd5WW+/y6DFdOQYNOu1vYpbqoiZnVRRjomh8/JSV3ICXZ4NfXxY9SBDAWxrUcQhhgEvRNX6BpjrU5PYw+ITY+HzC1H5DBWzbxb9+LmZsKycNLhFuoAqKqczAuivv/628TBvTVcJ7noKReIOfnwqi2BgWuG0GIn9jxiV98VskipdCQ7+FI7N7vHjfyBKstWUj0ISyXfItaqQJtgSB/VcvIjs3wH4ILoDNZWa0rAlB/DAB3ZKguxue59P7T531q0ZXHPKbNGpJLoKc4hNHfQxGfV0m92WndrK2Sg5CzJOMO0btig6sLerYZ7MZh9PYFE4Lm2JN/F6MOml00szz3LtCdKZV+bwt77VlGX++QSg5Ziy3e2iUKZFHg23zJj7TUM2HpRfJIDKhH6npswCXKydT/rf7l0yjTuXBFaxQnq4cs7vY7RuNJT1BIZQDY=
addons:
  ssh_known_hosts: 172.104.191.90
services:
- docker
branches:
  only:
  - master
sudo: required
script:
- docker build -t nodejs-api .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker tag nodejs-api $DOCKER_USER/nodejs-api:$TRAVIS_BUILD_NUMBER
- docker push $DOCKER_USER/nodejs-api:$TRAVIS_BUILD_NUMBER
- docker tag nodejs-api $DOCKER_USER/nodejs-api:latest
- docker push $DOCKER_USER/nodejs-api:latest
- scp deploy.sh root@172.104.191.90:/usr/deploy.sh
- ssh 'root@172.104.191.90' chmod +x /usr/deploy.sh
- ssh 'root@172.104.191.90' /usr/deploy.sh
